### ISSUE TITLE
Version 2.10.0 not available in Maven Central

### ISSUE THREAD

**Issue by lucasharsze** [wl-online-payments-direct/sdk-java#3]
Hello,

The last release available on Git seems to be the 2.10.0 but in maven Central, the last version available is 2.9.0 as you can see below : 

Last Release : 
[https://github.com/Ingenico/direct-sdk-java/releases/tag/2.10.0](https://github.com/Ingenico/direct-sdk-java/releases/tag/2.10.0)

Maven Repo page
[https://mvnrepository.com/artifact/com.ingenico.direct/direct-sdk-java](https://mvnrepository.com/artifact/com.ingenico.direct/direct-sdk-java)

Thanks for publishing the last one ;-) 

Regards,

**Comment by worldline-direct-support-team** [comment]
Hello!

A new release will be available on Maven later this week.

Kind regards
