### ISSUE TITLE
CreatePayment is giving error while using JavaScript and Java sdk

### ISSUE THREAD

**Issue by kurianjerin** [wl-online-payments-direct/sdk-java#5]
Hello,

We are using the JavaScript SDK and Java SDK together in our solution. In the client we use JavaScript SDK(https://docs.direct.worldline-solutions.com/en/integration/how-to-integrate/client-sdks/javascript#encryptandtransferpaymentdata) and in our server application we use Java SDK(https://docs.direct.worldline-solutions.com/en/integration/how-to-integrate/server-sdks/java)

If you look at the JavaScript sdk page at number "6. finalise Transaction" it is mentioned that we need to send encrypted data to our server and call the "Create Payment" request.
For this "Create Payment" request we used the Java sdk to implement since it is readily available with the JAVA sdk. 

Here is how we created the paymentRequest. Please see the mocked code below.

```
//Java code. Please assume that we receive the encryptedCustomerInput to our server
CreatePaymentRequest createPaymentRequest = new CreatePaymentRequest();
createPaymentRequest.setEncryptedCustomerInput(...encryptedCustomerInput..);//Setting the encryptedCustomerInput passed from client application to the createPaymentRequest request
createPaymentRequest.setOrder(....order....); //Setting order information
MerchantClientInterface merchantClient = ...getMerchantClient()...//Here we initialized the worldline client and merchant interface mentioned in the JAVA sdk
CreatePaymentResponse createPaymentResponse = merchantClient.payments().createPayment(createPaymentRequest);
```

This call is returning the following exception

> "the Online Payments platform returned an incorrect request error response; statusCode=400; responseBody='{"errorId":"b3b7153a-b948-45a3-81b9-a7d7dc3c366b","errors":[{"errorCode":"30001131","category":"DIRECT_PLATFORM_ERROR","code":"1099","httpStatusCode":400,"id":"INVALID_VALUE","message":"INVALID_VALUE","propertyName":"SpecificInput","retriable":false},{"errorCode":"50001111","category":"PAYMENT_PLATFORM_ERROR","code":"20000000","httpStatusCode":400,"id":"PARAMETER_NOT_FOUND_IN_REQUEST","message":"PARAMETER_NOT_FOUND_IN_REQUEST","propertyName":"cardPaymentMethodSpecificInput.card.cardholderName","retriable":false}]}'"

We were following the "Create Payment" api documentation here(https://docs.direct.worldline-solutions.com/en/api-reference#tag/Payments/operation/CreatePaymentApi)

Can you please help with this issue and the following queries?

1. In our use-case if we use client and server sdks what are the required parameters to be passed to create a payment in the request body? If we pass "encryptedCustomerInput" do we need to pass the rest of the fields mentioned in the api?
2. Does the Java SDK can be used in the server side for this use-case or should we implement http calls ourself for WorldLine apis?

Thanks

**Comment by worldline-direct-support-team** [comment]
Hello kurianjerin,

Thank you for questions! Please see hereby our answers:

1. If you pass “encryptedCustomerInput”, you do not need to provide the fields that are already in there. Specifically, if you use the JavaScript SDK to set the payment product, and customer-entered payment details on the “PaymentRequest” before encryption, you will not need to provide a “card” object in the API.  The error you receive indicates that “cardHolderName” is missing. You should verify that you request this field from your users, and set it before encryption. (See “[5. Encrypt and transfer payment data](https://docs.direct.worldline-solutions.com/en/integration/how-to-integrate/client-sdks/javascript#encryptandtransferpaymentdata)” of the JavaScript SDK documentation for more details.)
2. You can definitely use the Java SDK to make the final Create Payment call. There is no need to implement your own http call.

Hopefully this will help you to resolve your issue!

Kind regards,
Worldline Support

**Comment by kurianjerin** [comment]
Thank you for the reply :) The error has gone after providing the "cardHolderName".

We are using the test data from here. https://docs.direct.worldline-solutions.com/en/integration/how-to-integrate/test-cases/index

We get the following error on calling the create payment.
`com.onlinepayments.DeclinedPaymentException: declined payment '4235923286_0' with status 'REJECTED'; statusCode=500; responseBody='{"errorId":"56f20960-8dfe-4c9b-aeec-39029fbea40c","errors":[{"errorCode":"60001057","category":"DIRECT_PLATFORM_ERROR","code":"9999","httpStatusCode":500,"id":"UNKNOWN_SERVER_ERROR","message":"UNKNOWN_SERVER_ERROR","retriable":false}],"paymentResult":{"creationOutput":{},"payment":{"paymentOutput":{"amountOfMoney":{"amount":1302,"currencyCode":"EUR"},"references":{"merchantReference":"0f3e0298d14d45f7a20db2308fc7f277"},"acquiredAmount":{"amount":0,"currencyCode":"EUR"},"customer":{"device":{"ipAddressCountryCode":"99"}},"cardPaymentMethodSpecificOutput":{"paymentProductId":1,"card":{"cardNumber":"************3103","expiryDate":"1125","bin":"44500222","countryCode":"IN"},"fraudResults":{"fraudServiceResult":"no-advice","cvvResult":"P"},"threeDSecureResults":{"eci":"7","xid":"NDIzNTkyMzI4Ng=="},"acquirerInformation":{"name":"ACQUIRER"}},"paymentMethod":"card"},"status":"REJECTED","statusOutput":{"errors":[{"errorCode":"60001057","category":"DIRECT_PLATFORM_ERROR","code":"9999","httpStatusCode":500,"id":"UNKNOWN_SERVER_ERROR","message":"UNKNOWN_SERVER_ERROR","retriable":false}],"isCancellable":false,"statusCategory":"UNSUCCESSFUL","statusCode":2,"isAuthorized":false,"isRefundable":false},"id":"4235923286_0"}}}'
`

We looked at the api troubleshooting page but we couldn't figure out the reason for this error. Can you please help with that?
https://docs.direct.worldline-solutions.com/en/integration/api-developer-guide/api-troubleshooting

**Comment by worldline-direct-support-team** [comment]
Hello kurianjerin,

Happy to hear that your initial issue was resolved! 

As for the issue with rejected authorization we would kindly ask you to submit a request through our [contact form](https://docs.direct.worldline-solutions.com/en/about/contact/) on the Documentation Portal. Our support team there is readily available to assist you in resolving the issue and answer any questions you may have specifically related to rejected transactions.

Kind regards,
Worldline Support Team

**Comment by kurianjerin** [comment]
@worldline-direct-support-team Thanks. I did that.
